sudo: required
language: c
services:
  - docker

compiler:
  - gcc
  - clang

env:
  - DOCKER_TAG=ubuntu-18.04
  - DOCKER_TAG=fedora-30
  - DOCKER_TAG=opensuse-leap
  - DOCKER_TAG=ubuntu-18.04 TPM2_TSS_VERSION=master

# only one build should report coverage stats
matrix:
  include:
  - env: ENABLE_COVERAGE=true DOCKER_TAG=ubuntu-18.04
    compiler: gcc

script:
  - ./.ci/travis.run

after_failure:
  - cat build/test-suite.log
