dist: trusty
# This is a lie: we don't need sudo but this is required to get an
# Ubuntu image with a libc that isn't ancient, and with cmocka libs.
sudo: required
dist: trusty

language: c
compiler:
  - gcc
  - clang-3.8

addons:
  coverity_scan:
    project:
      name: "01org/tpm2-tools"
      description: "Build submitted via Travis CI"
    notification_email: william.c.roberts@intel.com
    build_command_prepend: "./bootstrap && ./configure && make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan
  apt:
    packages:
    - autoconf-archive
    - openssl
    - libssl-dev
    - libcurl4-openssl-dev
    - libdbus-1-dev
    - libglib2.0-dev
    - clang-3.8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RL61KKDlkyCIE6ZTV9HxnVIcrb5fsNQBKbq7d9vN7QqzAKbd1qedr7kzWZ+DMTi3F1e562DAzNPwNTN6KoLtXx0PxM3ETj1q/O1F5mk22gakLRpZAt0OowCEscSuzcMXdEcVxlNVB4Q3OM2OVJHgwJmh/pB05hx76xIfrrGkl+A8jc4zfjaHtUaTMFKUmeSuKwvTcMylbMVhCfuE9ALtvn6LssZ/roTQhsQ4f78X6grUKHvtQbXzQemTxjZD1mpmjGPlTAU9AnAvb8DmVmWNWyf3uNVElHeeplYLhiDkWPomm84oBH8Npxl+GRmvvmAsuCOkfE0AoC7WL4cFzvsFQ7iZcioF6MFoQH+QVZCvsRPRzxs36tJUXteNJZm4PBnpPpgnrRYx0VqMZ4CQLqZVPwlZUB0VC9amM1xYO/QRETV1XfcS7GqGH+G3hXR3ApyYPX2gLl8fy1M1RawdIGKOZXTo44pBOM1iws+Hrc2rqg5NFamfT4FIO1O9z3kHVEkh5AlTyYa7HJ5iuUb8ilyzZ7MI0Xlw4CJYNgzF/3TGk0cFMghJ/YY0Zd5CoVkBK31ENJ06k21DfuD4xyFVz4HpZJzcoJufkbXSc9HbGNKWgxAEzQrUDDQk9zaPzUe4hTVFYc3mQLKO/FPo+OQ/xxOsZIVAqYZD7xtbX+c6cBVFdks="

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install: 
    - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm532.tar
    - sha256sum ibmtpm532.tar | grep -q abc0b420257917ccb42a9750588565d5e84a2b4e99a6f9f46c3dad1f9912864f
    - mkdir ibmtpm532 && pushd ibmtpm532 && tar xzf ../ibmtpm532.tar && pushd ./src && make
    - ./tpm_server &
    - popd && popd
    - git clone https://github.com/01org/TPM2.0-TSS.git
    - pushd TPM2.0-TSS
    - git apply ../.ci/0001-TSS2_Sys_LoadExternal-Fix-marshaling-error.patch
    - ./bootstrap && ./configure && make -j$(nproc)
    - sudo ../.ci/travis-tss-install.sh
    - popd
    - sudo ldconfig /usr/local/lib
    - git clone https://github.com/01org/tpm2-abrmd.git
    - pushd tpm2-abrmd
    - ./bootstrap && ./configure --with-dbuspolicydir=/etc/dbus-1/system.d && make -j$(nproc) && sudo make install && popd
    - sudo mkdir -p /var/lib/tpm
    - sudo groupadd tss && sudo useradd -M -d /var/lib/tpm -s /bin/false -g tss tss
    - sudo pkill -HUP dbus-daemon
    - sudo -u tss tpm2-abrmd --tcti=socket &
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka-dev_1.0.1-2_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka0_1.0.1-2_amd64.deb
    - sha256sum libcmocka-dev_1.0.1-2_amd64.deb | grep -q edb0dcfa14893b0a03375c4fe3b852043ce8fca8f2397cde340562554f6d50eb
    - sha256sum libcmocka0_1.0.1-2_amd64.deb | grep -q 797155b45a8288a860c4ed9dd3f161420f09ebf362de30166d9f6b98bfc27dd0
    - sudo dpkg -i libcmocka0_1.0.1-2_amd64.deb
    - sudo dpkg -i libcmocka-dev_1.0.1-2_amd64.deb

script:
    - ./.ci/travis-build-and-run-tests.sh

after_failure:
   - cat build/test-suite.log
